const Types = {
  IS_USER_MODAL_OPEN: '@IS_USER_MODAL_OPEN',
  IS_BAG_MODAL_OPEN: '@IS_BAG_MODAL_OPEN',

  USER_SIGN_IN: '@USER_SIGN_IN',
  USER_SIGN_UP: '@USER_SIGN_UP',
  USER_SIGN_OUT: 'USER_SIGN_OUT',

  VALIDATE_USER: '@VALIDATE_USER',
  INVALID_USER: '@INVALID_USER',

  SIGN_IN_SLIDER: '@SIGN_IN_SLIDER',
  SIGN_UP_SLIDER: '@SIGN_UP_SLIDER',

  LOAD_SIGN_IN_SUBMIT: 'LOAD_SIGN_IN_SUBMIT',

  LAST_URL: '@LAST_URL',

  PRODUCT_STATE: '@PRODUCT_STATE',
  PRODUCT_LOADING: '@PRODUCT_LOADING',

  ADD_CART: '@ADD_CART_ITEM',
  REMOVE_ITEM_FROM_CART: '@REMOVE_ITEM_CART',

  CHECKOUT: '@CHECKOUT',

  INCREASE_QNT_ITEM_MORE_ONE: '@INCREASE_QNT_ITEM_MORE_ONE',
  DECREASE_QNT_ITEM_LESS_ONE: '@DECREASE_QNT_ITEM_LESS_ONE',
  CHANGE_QNT_ITEM_INPUT: '@CHANGE_QNT_ITEM_INPUT'
};

export default Types;
